/** @jest-environment jsdom */
/**
 * Automated accessibility (jest-axe) tests for the project's most-used UI
 * surfaces.
 *
 * These tests render each component in isolation and run axe-core against
 * the rendered DOM. Adding `expect(...).toHaveNoViolations()` lets CI
 * surface any new a11y regression automatically.
 *
 * The default Jest `testEnvironment` is `node`, so this file opts into
 * jsdom via the `@jest-environment` pragma. The custom matcher
 * `toHaveNoViolations` is registered globally by `jest.setup.a11y.ts`.
 */
import React from 'react';

import './a11y-mocks';
import { renderAndCheckA11y, summariseViolations } from './__fixtures__/a11yTestUtils';
import { ErrorInline } from '../ErrorInline';
import { ErrorBoundary } from '../ErrorBoundary';
import { ActivityCenter } from '../ActivityCenter';
import { Navbar } from '../Navbar';
import { EvidenceArtifactViewer } from '../EvidenceArtifactViewer';
import type { EvidenceArtifact } from '@/types/evidence-artifact';

const mockArtifact: EvidenceArtifact = {
    id: 'a11y-artifact-1',
    metadata: {
        id: 'a11y-meta-1',
        type: 'image',
        filename: 'a11y-image.jpg',
        mimeType: 'image/jpeg',
        size: 2048,
        uploadedAt: new Date('2024-01-01T00:00:00Z'),
        uploadedBy: 'a11y-tester',
        piiDetected: false,
    },
    content: 'data:image/jpeg;base64,ZmFrZQ==',
    redactionState: {
        level: 'none',
        regions: [],
        autoGeneratedRegions: [],
        manuallyReviewedRegions: [],
        lastModified: new Date('2024-01-01T00:00:00Z'),
        modifiedBy: 'a11y-tester',
    },
    permissions: {
        canViewOriginal: true,
        canViewRedacted: true,
        canModifyRedactions: false,
        canApproveRedactions: false,
        role: 'viewer',
    },
};

describe('Automated accessibility tests (jest-axe)', () => {
    it('ErrorInline (banner variant) has no critical violations', async () => {
        const { axeReport } = await renderAndCheckA11y(
            <ErrorInline
                error="Unable to reach the wallet service."
                onRetry={() => undefined}
                onClose={() => undefined}
                variant="banner"
            />,
        );

        expect(axeReport.violations).toEqual([]);
    });

    it('ErrorInline (card variant) has no critical violations', async () => {
        const { axeReport } = await renderAndCheckA11y(
            <ErrorInline
                error="Network connectivity issue detected."
                onRetry={() => undefined}
                onClose={() => undefined}
                variant="card"
            />,
        );

        expect(axeReport.violations).toEqual([]);
    });

    it('ActivityCenter bell trigger and panel have no violations', async () => {
        const { axeReport } = await renderAndCheckA11y(
            <main>
                <h1>Activity test</h1>
                <ActivityCenter />
            </main>,
        );

        expect(axeReport.violations).toEqual([]);
    });

    it('Navbar navigation has no critical violations', async () => {
        const { axeReport } = await renderAndCheckA11y(
            <main>
                <h1>Dashboard</h1>
                <Navbar />
            </main>,
        );

        if (axeReport.violations.length > 0) {
            // Surface a human-readable breakdown so CI failures are easy to triage.
            // eslint-disable-next-line no-console
            console.error('Navbar a11y violations:\n' + summariseViolations(axeReport.violations));
        }
        expect(axeReport.violations).toEqual([]);
    });

    it('ErrorBoundary fallback UI has no critical violations', async () => {
        // Suppress the noisy console.error from React's error boundary logging.
        const errorSpy = jest.spyOn(console, 'error').mockImplementation(() => undefined);

        class ThrowingComponent extends React.Component {
            override render(): React.ReactNode {
                throw new Error('forced error for boundary test');
            }
        }

        const { result, axeReport } = await renderAndCheckA11y(
            <ErrorBoundary>
                <ThrowingComponent />
            </ErrorBoundary>,
        );

        errorSpy.mockRestore();
        // Touch result so the linter doesn't complain about the unused binding.
        expect(result.container).toBeDefined();
        expect(axeReport.violations).toEqual([]);
    });

    it('EvidenceArtifactViewer (read-only) has no critical violations', async () => {
        const { axeReport } = await renderAndCheckA11y(
            <main>
                <h1>Artifact viewer</h1>
                <EvidenceArtifactViewer artifact={mockArtifact} />
            </main>,
        );

        expect(axeReport.violations).toEqual([]);
    });
});
